filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]   
  index: "cdc-events-%{+yyyy.MM.dd}"
